<a href="https://colab.research.google.com/github/Ramapatil-26/ML/blob/main/LogesticRegression2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split

In [2]:
import numpy as np
import pandas as pd

from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split

In [6]:
X = np.array([
    [20000, 500],
    [25000, 550],
    [30000, 600],
    [38000, 680],
    [40000, 700],
    [45000, 720],
    [48000, 730],
    [50000, 750]
])

y = np.array([0, 0, 0, 1, 1, 1, 1, 1])


In [7]:
print(type(X))

<class 'numpy.ndarray'>


In [8]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size= 0.2,random_state = 11)

In [9]:
X_train

array([[40000,   700],
       [45000,   720],
       [50000,   750],
       [38000,   680],
       [20000,   500],
       [25000,   550]])

In [10]:
y_train

array([1, 1, 1, 1, 0, 0])

In [11]:
X_test

array([[30000,   600],
       [48000,   730]])

In [12]:
y_test

array([0, 1])

In [13]:
from sklearn.linear_model import LogisticRegression

m = LogisticRegression()

In [14]:
m.fit(X_train,y_train)

LogisticRegression()

In [15]:
y_pred =m.predict(X_test)
print(y_pred)

[0 1]


In [16]:
a = accuracy_score(y_pred,y_test)
print(a)

1.0


In [17]:
hours = np.array ([[6]])

In [18]:
output= m.predict(X_test)
print(output)

[0 1]


In [19]:
prob=m.predict_proba(X_test)

In [20]:
print("probability of Not Approved",prob[0][0])
print("Probability of Approved",prob[0][1])

probability of Not Approved 0.7975378794482849
Probability of Approved 0.20246212055171509


In [24]:
if prob[0][1] >= 0.10:
  print("Loan Approved")
else:
  print("Loan Not Approved")

Loan Approved
